// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Core.Data;

#nullable disable

namespace Server.Core.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Data.ModuleDBEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Agression")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("BehaviourIDs")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("GraphicalRepresentationID")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHunger")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean");

                    b.Property<int>("ReproductionNeed")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Modules", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Agression = 1,
                            BehaviourIDs = new[] { 101, 212, 307, 405 },
                            Damage = 1,
                            GraphicalRepresentationID = 0,
                            MaxHealth = 80,
                            MaxHunger = 80,
                            Name = "Red Plant",
                            Official = true,
                            ReproductionNeed = 10,
                            Type = 2
                        },
                        new
                        {
                            ID = -2,
                            Agression = 2,
                            BehaviourIDs = new[] { 101, 206, 305, 405 },
                            Damage = 2,
                            GraphicalRepresentationID = 1,
                            MaxHealth = 70,
                            MaxHunger = 70,
                            Name = "Blue Plant",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 2
                        },
                        new
                        {
                            ID = -3,
                            Agression = 4,
                            BehaviourIDs = new[] { 105, 201, 307, 405 },
                            Damage = 5,
                            GraphicalRepresentationID = 6,
                            MaxHealth = 70,
                            MaxHunger = 70,
                            Name = "Purple Plant",
                            Official = true,
                            ReproductionNeed = 4,
                            Type = 2
                        },
                        new
                        {
                            ID = -4,
                            Agression = 4,
                            BehaviourIDs = new[] { 103, 208, 308, 403 },
                            Damage = 4,
                            GraphicalRepresentationID = 2,
                            MaxHealth = 60,
                            MaxHunger = 80,
                            Name = "Pig",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 2
                        },
                        new
                        {
                            ID = -5,
                            Agression = 7,
                            BehaviourIDs = new[] { 101, 210, 301, 402 },
                            Damage = 7,
                            GraphicalRepresentationID = 3,
                            MaxHealth = 70,
                            MaxHunger = 90,
                            Name = "Boar",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 2
                        },
                        new
                        {
                            ID = -6,
                            Agression = 3,
                            BehaviourIDs = new[] { 103, 207, 305, 402 },
                            Damage = 2,
                            GraphicalRepresentationID = 4,
                            MaxHealth = 40,
                            MaxHunger = 50,
                            Name = "White rabbit",
                            Official = true,
                            ReproductionNeed = 10,
                            Type = 2
                        },
                        new
                        {
                            ID = -7,
                            Agression = 2,
                            BehaviourIDs = new[] { 103, 207, 303, 402 },
                            Damage = 2,
                            GraphicalRepresentationID = 5,
                            MaxHealth = 40,
                            MaxHunger = 50,
                            Name = "Brown rabbit",
                            Official = true,
                            ReproductionNeed = 9,
                            Type = 2
                        },
                        new
                        {
                            ID = -8,
                            Agression = 1,
                            BehaviourIDs = new[] { 103, 212, 304, 403 },
                            Damage = 1,
                            GraphicalRepresentationID = 7,
                            MaxHealth = 50,
                            MaxHunger = 90,
                            Name = "Green slime",
                            Official = true,
                            ReproductionNeed = 8,
                            Type = 2
                        },
                        new
                        {
                            ID = -9,
                            Agression = 2,
                            BehaviourIDs = new[] { 101, 205, 306, 402 },
                            Damage = 3,
                            GraphicalRepresentationID = 8,
                            MaxHealth = 60,
                            MaxHunger = 90,
                            Name = "Blue slime",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 2
                        },
                        new
                        {
                            ID = -10,
                            Agression = 5,
                            BehaviourIDs = new[] { 105, 204, 301, 406 },
                            Damage = 7,
                            GraphicalRepresentationID = 9,
                            MaxHealth = 50,
                            MaxHunger = 80,
                            Name = "Red slime",
                            Official = true,
                            ReproductionNeed = 3,
                            Type = 2
                        },
                        new
                        {
                            ID = -11,
                            Agression = 7,
                            BehaviourIDs = new[] { 101, 201, 301, 405 },
                            Damage = 7,
                            GraphicalRepresentationID = 10,
                            MaxHealth = 90,
                            MaxHunger = 90,
                            Name = "Green orc",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 2
                        },
                        new
                        {
                            ID = -12,
                            Agression = 8,
                            BehaviourIDs = new[] { 105, 205, 301, 405 },
                            Damage = 5,
                            GraphicalRepresentationID = 11,
                            MaxHealth = 90,
                            MaxHunger = 80,
                            Name = "Blue orc",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 2
                        },
                        new
                        {
                            ID = -13,
                            Agression = 6,
                            BehaviourIDs = new[] { 105, 201, 307, 404 },
                            Damage = 10,
                            GraphicalRepresentationID = 12,
                            MaxHealth = 90,
                            MaxHunger = 80,
                            Name = "Darkgreen orc",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 2
                        },
                        new
                        {
                            ID = -14,
                            Agression = 6,
                            BehaviourIDs = new[] { 102, 203, 302, 405 },
                            Damage = 7,
                            GraphicalRepresentationID = 13,
                            MaxHealth = 90,
                            MaxHunger = 90,
                            Name = "Vampire",
                            Official = true,
                            ReproductionNeed = 3,
                            Type = 2
                        },
                        new
                        {
                            ID = -15,
                            Agression = 8,
                            BehaviourIDs = new[] { 102, 209, 302, 404 },
                            Damage = 5,
                            GraphicalRepresentationID = 14,
                            MaxHealth = 90,
                            MaxHunger = 80,
                            Name = "Blue vampire",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 2
                        },
                        new
                        {
                            ID = -16,
                            Agression = 6,
                            BehaviourIDs = new[] { 102, 202, 302, 403 },
                            Damage = 9,
                            GraphicalRepresentationID = 15,
                            MaxHealth = 90,
                            MaxHunger = 80,
                            Name = "Red vampire",
                            Official = true,
                            ReproductionNeed = 2,
                            Type = 2
                        },
                        new
                        {
                            ID = -17,
                            Agression = 0,
                            BehaviourIDs = new int[0],
                            Damage = 10,
                            GraphicalRepresentationID = 16,
                            MaxHealth = 100,
                            MaxHunger = 100,
                            Name = "Human",
                            Official = true,
                            ReproductionNeed = 0,
                            Type = 1
                        },
                        new
                        {
                            ID = -18,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 17,
                            MaxHealth = 30,
                            MaxHunger = 10,
                            Name = "Cosmo",
                            Official = true,
                            ReproductionNeed = 7,
                            Type = 4
                        },
                        new
                        {
                            ID = -19,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 18,
                            MaxHealth = 30,
                            MaxHunger = 10,
                            Name = "Daffodil",
                            Official = true,
                            ReproductionNeed = 7,
                            Type = 4
                        },
                        new
                        {
                            ID = -20,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 19,
                            MaxHealth = 40,
                            MaxHunger = 10,
                            Name = "Daisy",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 4
                        },
                        new
                        {
                            ID = -21,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 20,
                            MaxHealth = 60,
                            MaxHunger = 20,
                            Name = "Lavender",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 4
                        },
                        new
                        {
                            ID = -22,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 21,
                            MaxHealth = 50,
                            MaxHunger = 10,
                            Name = "Lily",
                            Official = true,
                            ReproductionNeed = 7,
                            Type = 4
                        },
                        new
                        {
                            ID = -23,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 22,
                            MaxHealth = 60,
                            MaxHunger = 20,
                            Name = "LilyOfTheValley",
                            Official = true,
                            ReproductionNeed = 8,
                            Type = 4
                        },
                        new
                        {
                            ID = -24,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 23,
                            MaxHealth = 70,
                            MaxHunger = 30,
                            Name = "Orchid",
                            Official = true,
                            ReproductionNeed = 4,
                            Type = 4
                        },
                        new
                        {
                            ID = -25,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 24,
                            MaxHealth = 50,
                            MaxHunger = 10,
                            Name = "Pansy",
                            Official = true,
                            ReproductionNeed = 10,
                            Type = 4
                        },
                        new
                        {
                            ID = -26,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 25,
                            MaxHealth = 70,
                            MaxHunger = 10,
                            Name = "Poppy",
                            Official = true,
                            ReproductionNeed = 8,
                            Type = 4
                        },
                        new
                        {
                            ID = -27,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 26,
                            MaxHealth = 100,
                            MaxHunger = 30,
                            Name = "Rose",
                            Official = true,
                            ReproductionNeed = 4,
                            Type = 4
                        },
                        new
                        {
                            ID = -28,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 27,
                            MaxHealth = 80,
                            MaxHunger = 40,
                            Name = "Sunflower",
                            Official = true,
                            ReproductionNeed = 6,
                            Type = 4
                        },
                        new
                        {
                            ID = -29,
                            Agression = 0,
                            BehaviourIDs = new[] { 104, 213, 309, 401 },
                            Damage = 0,
                            GraphicalRepresentationID = 28,
                            MaxHealth = 100,
                            MaxHunger = 20,
                            Name = "Tulip",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
