// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Core.Data;

#nullable disable

namespace Server.Core.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Data.ModuleDBEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Agression")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("BehaviourIDs")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("GraphicalRepresentationID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean");

                    b.Property<int>("ReproductionNeed")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Modules", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Agression = 5,
                            BehaviourIDs = new int[0],
                            Damage = 5,
                            GraphicalRepresentationID = 1,
                            Name = "Human module",
                            Official = true,
                            ReproductionNeed = 5,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
