name: Enforce PR Source Branch

on:
  pull_request:
    branches:
      - master

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from dev
        run: |
          if [[ "${{ github.head_ref }}" != "development" ]]; then
            echo "Pull requests to main must come from the dev branch."
            exit 1
          fi
